In [1]:
import numpy as np

In [2]:
arr_ran = np.arange(0,10,1)
arr_ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr_ran)

numpy.ndarray

In [4]:
arr = np.array(range(1,10))
print("Length:",len(arr))
print("Size:",arr.size)

Length: 9
Size: 9


In [5]:
arr = np.array([range(1,10)])
print("Length:",len(arr))
print("Size:",arr.size)

Length: 1
Size: 9


In [6]:
arr = np.arange(10)
arr.size*arr.itemsize

80

In [7]:
arr.nbytes

80

In [8]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr_2d.ndim

2

In [10]:
arr_2d.size

8

In [11]:
n_arr = np.random.rand(10)
n_arr

array([0.6369478 , 0.8461806 , 0.92844251, 0.09367267, 0.42237015,
       0.84544694, 0.71481181, 0.29387779, 0.8829227 , 0.37207691])

In [12]:
n_arr.shape   #shape: returns in tuple


(10,)

In [13]:
n_arr.shape   #shape: returns in tuple
(10,)

(10,)

In [14]:
n_arr

array([0.6369478 , 0.8461806 , 0.92844251, 0.09367267, 0.42237015,
       0.84544694, 0.71481181, 0.29387779, 0.8829227 , 0.37207691])

In [15]:
n_arr.shape

(10,)

In [16]:
n_arr.ndim

1

In [17]:
len(n_arr.shape)

1

In [18]:
len(n_arr.shape) == n_arr.ndim

True

In [19]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [20]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
arr_3d.ndim

3

In [22]:
arr_3d.shape

(1, 3, 3)

In [23]:
arr10 = np.random.random(10)
print(arr10)

[0.26425541 0.69655831 0.11320205 0.64405558 0.85356586 0.18504338
 0.29791529 0.63246974 0.66279571 0.94371086]


In [24]:
arr10 = np.random.rand(10)
arr10

array([0.55288076, 0.46990809, 0.86168559, 0.5687607 , 0.09588073,
       0.50706638, 0.02176127, 0.93479023, 0.29148581, 0.65661521])

In [25]:
arr_with_nega = np.random.randn(5)
arr_with_nega

array([-0.32199179, -1.70048577, -1.27772085, -0.33339631, -0.09085034])

In [26]:
random_25_arr = np.random.random(25,3)

TypeError: random() takes at most 1 positional argument (2 given)

In [ ]:
random_25_arr = np.random.rand(25,3)

In [ ]:
random_25_arr

In [27]:
work_on_index = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
work_on_index , work_on_index.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 (3, 4))

In [28]:
work_on_index[0][0]

1

In [ ]:
work_on_index[0]

In [ ]:
work_on_index[-1]

In [ ]:
work_on_slice = work_on_index

In [ ]:
work_on_slice[0:2] 

In [ ]:
work_on_slice[1:2,0:2] 

In [ ]:
work_on_slice[[0,-1]]

In [ ]:
work_on_slice[0:,-1]

In [ ]:
work_on_slice[0::2,-1:] 

In [ ]:
work_on_slice[0:3:2,0:-1:2]

In [ ]:
work_on_slice

In [ ]:
two_dim_arr = np.array([[10,20,30,40],[50,60,70,80]])
two_dim_arr

In [ ]:
two_dim_arr.shape

In [ ]:
two_dim_arr.T

In [ ]:
two_dim_arr.T.shape

In [ ]:
marks = [65,78,94,66,88,80,91]
marks = np.array(marks)
marks

In [ ]:
mean = np.mean(marks)
print(mean)

In [ ]:
alternative_mean = sum(marks)/len(marks)
print(alternative_mean)

In [ ]:
median = np.median(marks)
print(median)

In [ ]:
marks.sort()
alternative_median = marks[len(marks)//2]
print(alternative_median)

In [ ]:
variance = np.var(marks)
print(variance)

In [ ]:
sum = 0
for i in marks:
    sum += (i-marks.sum()/len(marks))**2

alternative_variance = sum/len(marks)
print("%.4f"%alternative_variance)

In [ ]:
std_deviation = np.std(marks)
print(std_deviation)

In [ ]:
alternative_std = np.sqrt(alternative_variance)
print("%.4f"%alternative_std)

In [ ]:
distibution = np.linspace(0,100,5)
distibution

In [ ]:
distibution = np.linspace(0,100,2)
distibution

In [ ]:
sum_arr_eg = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])

In [ ]:
sum_arr_eg

In [ ]:
sum_arr_eg.sum() 

In [ ]:
sum_arr_eg.sum(axis=0)

In [ ]:
sum_arr_eg.sum(axis=1)

In [ ]:
w = np.random.rand(2,3) 
x = np.random.rand(3,1)
w, x

In [ ]:
matrix_mul = np.matmul(w,x)
matrix_mul

In [ ]:
matrix_mul.shape

In [ ]:
dot_product = np.dot(w,x)

In [ ]:
np.exp(2)

In [ ]:
y = 1.4
m = 3
c = 0.4
z = y*m + c
sigmoid = 1/(1+np.exp(-z))
sigmoid

In [ ]:
np.log(10)

In [ ]:
np.log2(10)

In [ ]:
np.log10(10)